### ISSUE TITLE
Leader lines not displaying at v 1.3.4

### ISSUE THREAD

**Issue by dpsspatial** [haubourg/EasyCustomLabeling#15]
Leader lines aren't displaying anymore:

Testing on 2 machines (Windows 7, Linux Mint)

Both QGIS 2.14, ECL v 1.3.4

Anyone else seeing this?

**Comment by dpsspatial** [comment]
Just an update that old projects using the same version of the plugin still work - but for some reason I can't get a layer in a new project to show leader lines.

**Comment by haubourg** [comment]
Hi, sorry for the lag, I'm just changing job, location, almost all but women and children :)
You mean old project version was 2.12 and new broken one is 2.14 ? 
Could you try to open leader line style editor and check expressions set on dashed line pattern and transparency ? I suppose something has changed there. 
Could you post the two versions of qgis files? 
Cheers

**Comment by dpsspatial** [comment]
Thanks for the reply! Hope you're settled!!

So both projects are on v2.14 

One thing I'm noticing in my 'new' project (again on v2.14) is the LabelShowCO value is not being updated when I move the label - so when I set it manually the leader shows - but then when I move the label once again, the LabelShowCO value is re-set to 0.

I'm wondering if that's where the issue lies?

**Comment by dpsspatial** [comment]
OK changing the setting you mentioned to:

CASE WHEN LblShowCO = 1 THEN '2;1' ELSE '1;2' END

now shows the dashed leader. Let me dig in a bit more...

**Comment by dpsspatial** [comment]
So it seems deactivating the data defined override for the dash pattern brings the leader lines back... even though by defaul the 'use custom dash pattern' option is unchecked, the data defined override is enabled - deactivating this enables the leader lines. 

Not sure why this is! Have you been able to see anything similar?

**Comment by nboisteault** [comment]
Women! You keep all of them? Really?

Nicolas BOISTEAULT
Développeur Web/WebSIG
Observatoire Régional de l'Environnement
Téléport 4 Antarès - BP 50163 - 86962 Futuroscope Chasseneuil Cedex
Tél : 05 49 49 71 18
*Soyez Eco-responsable, n'imprimez que si nécessaire*

**Comment by haubourg** [comment]
> Women! You keep all of them? Really?
ok just my wife in fact, but she's worth it :-)

**Comment by haubourg** [comment]
> So it seems deactivating the data defined override for the dash pattern brings the leader lines back... even though by defaul the 'use custom dash pattern' option is unchecked, the data defined override is enabled - deactivating this enables the leader lines.

Yes I've seen that on some configurations already, without being able to reproduce it. It could be a dark combination of plugins that override some signals, or something related to packaging. Now that  geometray generators are here, I guess we could do a major update to improve one last time the plugin. In 3.0, I hope it's gonna be part of the core..

**Comment by dpsspatial** [comment]
Fair enough - well at least this was an exercise into seeing where the leader lines are styled! That in itself was valuable here... we use these a lot, so get in touch if this comes to a 'crowdsource' need to get this in core... since we have drastically reduced our ArcGIS bill, we might have some resources to get these types of improvements going! Thank you for your time and for this plugin!!!
