### ISSUE TITLE
[qgis 2.16] Problem of data coordinates

### ISSUE THREAD

**Issue by GlaDal** [haubourg/EasyCustomLabeling#18]
Dear Mr Haubourg, 

Here is my next problem. 5 persons on the last stage had the same problem. After having create a memory layer with EasyABC on a polygon layer, several labels don't appear for several object (the same objects for each person). We find the problem in the attribute table : on the column X an Y coordinates for the label, several numbers were registrated (I put an image of the table). This appear just after having create the memory layer. 

![easyabc_problem](https://cloud.githubusercontent.com/assets/7015197/19213184/ac3326a2-8d64-11e6-96ac-3b990c104055.png)

Thanks for all

**Comment by haubourg** [comment]
Hi, can you share the data set causing this?
Thanks. Régis

**Comment by spaceof7** [comment]
I think the problem I have is related, but I am using 2.18.1.  When I create a label layer for a line dataset all the X/Y coordinates are 0 and so labels aren't visible/editable unless I deactivate the data-defined: coordinates.  I've attached the shapefile.  Thanks!

Andrew
[major_rivers.zip](https://github.com/haubourg/EasyCustomLabeling/files/646980/major_rivers.zip)

**Comment by haubourg** [comment]
Thanks for the dataset, I check that

**Comment by haubourg** [comment]
OK, got it. 
The idea behind qgis labeling is that it uses NULL values to set that XY fields should not be used for pinned labeling and then let the native placement engine work. 
When you choose shapefile to store data, you loose the ability to store NULL values (this is a strong limitation of shapefile), and then XY are set to 0. You labels are drawn, but somewhere around 0,0 coordinates :). There is no workaround about it if you stick to shp. 

What I advise in the doc is to use memory layer saver to store labeling layers along the project file. If you want to store labels to a standard file or DB, you need to choose one that handles null values. I strongly suggest Spatialite then, but the general case is that layers are deeply linked to a map, then it make sense to use memory layer saver plugin. 
Hope that helps.

**Comment by GlaDal** [comment]
Hi, 
For my part, the problem occurred with memory layer.

Bye
