### ISSUE TITLE
Moving labels creates python error, no leader lines.

### ISSUE THREAD

**Issue by davidnfox** [haubourg/EasyCustomLabeling#25]
Traceback (most recent call last):
			  File "C:/Users/xxxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\EasyCustomLabeling\EasyCustomLabeling.py", line 219, in labelLayerModified
			    WKTLine = editGeom.exportToWkt()
			AttributeError: 'QgsGeometry' object has no attribute 'exportToWkt'

**Comment by dpsspatial** [comment]
Seeing this as well, on QGIS 3.2

**Comment by FERRATON** [comment]
I confirm the bug under QGIS 3.3
see also : https://gis.stackexchange.com/questions/276592/connectors-do-not-appear-automatically-in-easy-custom-labelling
recent news about https://github.com/qgis/QGIS-Enhancement-Proposals/issues/47 ?

**Comment by haubourg** [comment]
Hi, sorry for the lag, for some reason I was unsubscribed from my own repository notifications. 

I published a fixed version, 2.1. That should work now.

**Comment by davidnfox** [comment]
Thanks, haubourg.  Very helpful tool.
