### ISSUE TITLE
All labels rotating when only one is selected

### ISSUE THREAD

**Issue by MaelJezequel** [haubourg/EasyCustomLabeling#33]
Hello,

When I try to rotate a label, all labels are rotating in the same time. Is this normal ?

Thank you,

**Comment by haubourg** [comment]
Hi!
This plugin us deprecated since most of the features have been ported to QGIS core . I will probably set a maximum version to QGIS 3.12.  it is highly possible we have issues with more recent versions. 
Thanks for reporting however!

**Comment by MaelJezequel** [comment]
Hi. Thank you for your answer. This plugin is really helpful.
